// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1P6KYs_ud9IEwAIEwIbJHtgyxEacZBK0',
    appId: '1:474959161797:web:cc8ddf6376c2cd2f87c3ac',
    messagingSenderId: '474959161797',
    projectId: 'edu-pfe',
    authDomain: 'edu-pfe.firebaseapp.com',
    storageBucket: 'edu-pfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2aL2i994qp62iNGIqENPUCF3_F4NFGk',
    appId: '1:474959161797:android:cf56f269fdec0da587c3ac',
    messagingSenderId: '474959161797',
    projectId: 'edu-pfe',
    storageBucket: 'edu-pfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkv5nypa2HDXCRYPYkSpqM8XxETNJSgtA',
    appId: '1:474959161797:ios:289968a09b3e7be787c3ac',
    messagingSenderId: '474959161797',
    projectId: 'edu-pfe',
    storageBucket: 'edu-pfe.appspot.com',
    iosBundleId: 'com.example.edupinacle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkv5nypa2HDXCRYPYkSpqM8XxETNJSgtA',
    appId: '1:474959161797:ios:289968a09b3e7be787c3ac',
    messagingSenderId: '474959161797',
    projectId: 'edu-pfe',
    storageBucket: 'edu-pfe.appspot.com',
    iosBundleId: 'com.example.edupinacle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1P6KYs_ud9IEwAIEwIbJHtgyxEacZBK0',
    appId: '1:474959161797:web:16417c4d2c21179887c3ac',
    messagingSenderId: '474959161797',
    projectId: 'edu-pfe',
    authDomain: 'edu-pfe.firebaseapp.com',
    storageBucket: 'edu-pfe.appspot.com',
  );
}
